server:
  port: 9527

spring:
  application:
    name: cloud-gateway #以微服务注册进consul或nacos服务列表内
  cloud:
    consul: #配置consul地址
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service                #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/get/**              # 断言，路径相匹配的进行路由
            - My=diamond
#            - Method=POST
#            - name: My
#              args:
#                userType: diamond
#             - Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
#            - Cookie=username,lp
#            - Before=2024-05-26T16:05:00.659585500+08:00[Asia/Shanghai] #在这之前可以访问
#            - Between=2024-05-26T16:02:00.659585500+08:00[Asia/Shanghai],2024-05-26T16:20:00.659585500+08:00[Asia/Shanghai] #在这个时间段可以访问
            - After=2024-05-26T16:02:00.659585500+08:00[Asia/Shanghai]   #在这之后可以访问


        - id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service                 #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/info/**              # 断言，路径相匹配的进行路由

        - id: pay_routh3 #pay_routh3
          uri: lb://cloud-payment-service                #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/filter/**              # 断言，路径相匹配的进行路由
          filters:
            - AddRequestHeader=X-Request-atguigu1,atguiguValue1  # 请求头kv，若一头含有多参则重写一行设置
            - AddRequestHeader=X-Request-atguigu2,atguiguValue2
            - My=atguigu

        - id: pay_routh4 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service                 #匹配后提供服务的路由地址
          predicates:
            - Path=/gateway/**
          filters:
#            - SetPath=/pay/gateway/{segment}
            - PrefixPath=/pay